package com.huasco.greendao.gen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.huasco.greendao.gen.CacheDaoModel;
import com.huasco.greendao.gen.TempCacheDaoModel;

import com.huasco.greendao.gen.CacheDaoModelDao;
import com.huasco.greendao.gen.TempCacheDaoModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cacheDaoModelDaoConfig;
    private final DaoConfig tempCacheDaoModelDaoConfig;

    private final CacheDaoModelDao cacheDaoModelDao;
    private final TempCacheDaoModelDao tempCacheDaoModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cacheDaoModelDaoConfig = daoConfigMap.get(CacheDaoModelDao.class).clone();
        cacheDaoModelDaoConfig.initIdentityScope(type);

        tempCacheDaoModelDaoConfig = daoConfigMap.get(TempCacheDaoModelDao.class).clone();
        tempCacheDaoModelDaoConfig.initIdentityScope(type);

        cacheDaoModelDao = new CacheDaoModelDao(cacheDaoModelDaoConfig, this);
        tempCacheDaoModelDao = new TempCacheDaoModelDao(tempCacheDaoModelDaoConfig, this);

        registerDao(CacheDaoModel.class, cacheDaoModelDao);
        registerDao(TempCacheDaoModel.class, tempCacheDaoModelDao);
    }
    
    public void clear() {
        cacheDaoModelDaoConfig.clearIdentityScope();
        tempCacheDaoModelDaoConfig.clearIdentityScope();
    }

    public CacheDaoModelDao getCacheDaoModelDao() {
        return cacheDaoModelDao;
    }

    public TempCacheDaoModelDao getTempCacheDaoModelDao() {
        return tempCacheDaoModelDao;
    }

}
